// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaQ1rbtIGgQDYUklIBwCPFxduZ_D5qG-U',
    appId: '1:566987714576:web:df9056e820ec1948ba1a95',
    messagingSenderId: '566987714576',
    projectId: 'sglab-desk',
    authDomain: 'sglab-desk.firebaseapp.com',
    storageBucket: 'sglab-desk.firebasestorage.app',
    measurementId: 'G-BEPJQDYKFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnlYAOnh8gMFCvbA8xqaKOTAUbbJfBk7c',
    appId: '1:566987714576:android:07d9865e67f8f133ba1a95',
    messagingSenderId: '566987714576',
    projectId: 'sglab-desk',
    storageBucket: 'sglab-desk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxipvX_tKdozpvX_0NarTL9-_nfWqtuS4',
    appId: '1:566987714576:ios:681f4256b1fd5612ba1a95',
    messagingSenderId: '566987714576',
    projectId: 'sglab-desk',
    storageBucket: 'sglab-desk.firebasestorage.app',
    androidClientId: '566987714576-bv41iva2uftt19kg70v7nmvgf9492slj.apps.googleusercontent.com',
    iosClientId: '566987714576-ggln93tu6ufb6na3ne6fliqu6v6ijtpq.apps.googleusercontent.com',
    iosBundleId: 'com.sglab.sglabDesk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxipvX_tKdozpvX_0NarTL9-_nfWqtuS4',
    appId: '1:566987714576:ios:681f4256b1fd5612ba1a95',
    messagingSenderId: '566987714576',
    projectId: 'sglab-desk',
    storageBucket: 'sglab-desk.firebasestorage.app',
    androidClientId: '566987714576-bv41iva2uftt19kg70v7nmvgf9492slj.apps.googleusercontent.com',
    iosClientId: '566987714576-ggln93tu6ufb6na3ne6fliqu6v6ijtpq.apps.googleusercontent.com',
    iosBundleId: 'com.sglab.sglabDesk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBggXBQjQuvXwniHyCvLLfFGtsKxs8qEZg',
    appId: '1:566987714576:web:8d1e0fa0868b1968ba1a95',
    messagingSenderId: '566987714576',
    projectId: 'sglab-desk',
    authDomain: 'sglab-desk.firebaseapp.com',
    storageBucket: 'sglab-desk.firebasestorage.app',
    measurementId: 'G-EX8Q03LJYZ',
  );
}
